@echo off
REM ================================================================
REM renAIssance Framework - Build Script (Windows)
REM Generated by configure.py - Verified 2025-12-23
REM Build Directory: build/windows-msvc-release
REM ================================================================

setlocal enabledelayedexpansion

REM Get script directory (project root) and remove trailing backslash
set PROJECT_ROOT=%~dp0
set PROJECT_ROOT=%PROJECT_ROOT:~0,-1%

echo [INFO] renAIssance Framework Build (Windows)
echo [INFO] Build Directory: build/windows-msvc-release
echo [INFO] Parallel Jobs: 30

REM Key step: Initialize Visual Studio Developer Command Prompt environment
echo [INFO] Initializing Visual Studio Developer Command Prompt...
call "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build/vcvars64.bat"

if %errorlevel% neq 0 (
    echo [ERROR] Failed to initialize Visual Studio environment
    echo [INFO] Please check Visual Studio installation
    exit /b 1
)

REM Clean and create build directory (using correct directory name)
if exist build/windows-msvc-release (
    echo [INFO] Cleaning existing build directory...
    rmdir /s /q build/windows-msvc-release
)
mkdir build/windows-msvc-release

REM Configure CMake - using verified parameters from 2025-12-23
REM Note: Use -B and -S to explicitly specify build and source directories
echo [INFO] Configuring with CMake...
cmake -G Ninja ^
    -S "%PROJECT_ROOT%" ^
    -B build/windows-msvc-release ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DCMAKE_CXX_COMPILER=cl ^
    -DCMAKE_TOOLCHAIN_FILE=T:/Softwares/vcpkg/scripts/buildsystems/vcpkg.cmake ^
    -DTR_SCENE_PC_CUDA=ON -DTR_USE_CUDA=ON -DTR_USE_MUSA=OFF -DTR_USE_ONEDNN=ON -DTR_USE_XNNPACK=ON -DTR_USE_STB=ON -DTR_USE_LIBJPEG=ON -DTR_USE_ZLIB=ON -DTR_USE_LIBCURL=ON -DTR_USE_MIMALLOC=ON -DTR_USE_SIMD=ON

if %errorlevel% neq 0 (
    echo [ERROR] CMake configuration failed
    echo [INFO] This might be due to missing dependencies or path issues
    exit /b 1
)

REM Build all targets
echo [INFO] Building all targets with Ninja...
cmake --build build/windows-msvc-release --parallel 30

if %errorlevel% neq 0 (
    echo [ERROR] Build failed
    echo [INFO] This might be due to missing dependencies or compilation errors
    exit /b 1
)

echo [OK] Build completed successfully!
echo [INFO] Build artifacts are in: build/windows-msvc-release

REM Return to root directory
cd "%PROJECT_ROOT%"
endlocal
